/******************************************
 * SLIDE2STUDY FRONTEND LOGIC (MAIN SCRIPT)
 *
 * This file implements the full client-side flow for the Slide2Study app:
 * - Loads slide text byextracting text from a user-uploaded PDF using pdf.js.
 * - Maintains application state (current slide, Bloom level, free-talk mode).
 * - Communicates with the backend for slide summaries, Bloom-level questions,
 *   grading, and free-talk responses.
 * - Manages all UI behavior, including chat rendering, progress bar updates,
 *   slide counters, and drag-and-drop file upload.
 * - Implements the main study loop: show summary → (optional free talk) →
 *   remember → understand → apply → next slide.
 *
 * Note that the majority of this code was generated by GPT-5.0.
 ******************************************/


/******************************************
 * BASIC DOM ELEMENTS
 ******************************************/
const typingForm = document.querySelector(".typing-form");
const chatList = document.querySelector(".chat-list");
const deleteChatButton = document.querySelector("#delet-chat-button");
let isResponseGenerating = false;
const BASE_URL = "http://127.0.0.1:5000";

/******************************************
 * load in slides from local csv for testing
 ******************************************/
let localSlides = {};

async function loadLocalSlides() {
  const res = await fetch("sample_slides.csv");
  const csvText = await res.text();
  //console.log("CSV Text:", csvText);

  const parsed = Papa.parse(csvText, {
    header: true,
    skipEmptyLines: true,
  });
  //console.log("Parsed CSV:", parsed);

  parsed.data.forEach((row) => {
    const index = parseInt(row.slide_index);
    const text = row.text;
    localSlides[index] = text;
  });

  //console.log("Local Slides Object:", localSlides[4]);
}
loadLocalSlides();

/******************************************
 * extract text from PDF using pdf.js
 ******************************************/
async function extractPdfText(file) {
  const arrayBuffer = await file.arrayBuffer();
  const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;

  const numPages = pdf.numPages;
  console.log("PDF pages:", numPages);

  localSlides = {}; // reset

  for (let i = 1; i <= numPages; i++) {
    const page = await pdf.getPage(i);
    const content = await page.getTextContent();

    const strings = content.items.map((item) => item.str);
    const pageText = strings.join(" ");

    console.log(pageText);
    localSlides[i] = pageText;
  }

  console.log("Extracted PDF text:", localSlides);
}

/******************************************
 * FRONTEND STATE MACHINE (UNIFIED OBJECT)
 ******************************************/
const state = {
  currentSlide: 4,
  totalSlides: 26,
  bloomOrder: ["content", "remember", "understand", "apply"],
  bloomIndex: 0,
  freetalk: false,
  currentQuestion: null,
  freeTalkHistory: [],
};

/******************************************
 * FILE UPLOAD — KEEPING YOUR EXISTING FLOW
 ******************************************/
const dropZone = document.getElementById("drop-zone");
const fileInput = document.getElementById("file-input");

dropZone?.addEventListener("click", () => fileInput.click());
fileInput?.addEventListener("change", (e) => handleFiles(e.target.files));

dropZone?.addEventListener("dragover", (e) => {
  e.preventDefault();
  dropZone.style.borderColor = "#007bff";
});
dropZone?.addEventListener("dragleave", () => {
  dropZone.style.borderColor = "#aaa";
});
dropZone?.addEventListener("drop", (e) => {
  e.preventDefault();
  dropZone.style.borderColor = "#aaa";
  handleFiles(e.dataTransfer.files);
});

async function handleFiles(files) {
  if (!files.length) return;

  const file = files[0];

  // Extract PDF text locally
  await extractPdfText(file);

  // Continue your UI transitions…
  document.getElementById("initial-screen")?.classList.add("hidden");
  setTimeout(() => {
    document.getElementById("initial-screen").style.display = "none";
    document.querySelector(".chat-container").classList.remove("hidden");
  }, 300);

  // Start session on page 1
  state.currentSlide = 5;
  loadNextSummary();
}

/******************************************
 * slide count update
 ******************************************/
function updateSlideCounter() {
  const counter = document.querySelector(".slide-counter");
  counter.textContent = `Slide: ${state.currentSlide} / ${state.totalSlides}`;
}

/******************************************
 * CHAT UI HELPERS
 ******************************************/
function addMessage(text, type) {
  const div = document.createElement("div");
  div.classList.add("message", type);

  div.innerHTML = `
    <div class="message-content">
      <img src="${type === "incoming" ? "image/gpt.jpg" : "image/user.jpg"}" 
           class="avatar">
      <p class="text">${text}</p>
    </div>
  `;

  if (state.freetalk) {
    state.freeTalkHistory.push({ role: type, content: text });
  }

  chatList.appendChild(div);
  chatList.scrollTo(0, chatList.scrollHeight);
}

/******************************************
 * PROGRESS BAR HIGHLIGHTING
 ******************************************/
function updateProgressBar() {
  const steps = document.querySelectorAll(".progress-bar .step");
  steps.forEach((step) => step.classList.remove("filled", "enlarged"));

  let active;

  if (state.bloomIndex === 0) active = "content";
  if (state.bloomIndex === 1) active = "remember";
  if (state.bloomIndex === 2) active = "understand";
  if (state.bloomIndex === 3) active = "apply";

  steps.forEach((step) => {
    if (step.dataset.endpoint === active) {
      step.classList.add("filled", "enlarged");
    }
  });
}

/******************************************
 * BACKEND HELPERS
 ******************************************/
async function fetchSummary(slideIndex) {
  const slideText = localSlides[slideIndex];

  const res = await fetch(`${BASE_URL}/summary`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ slide_text: slideText }),
  });

  return res.json();
}

async function fetchQuestion(slideIndex, level) {
  const slideText = localSlides[slideIndex];
  console.log("Fetching question for:", slideText, "level:", level);

  const res = await fetch(`${BASE_URL}/question`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      slide_text: slideText,
      level: level,
    }),
  });

  return res.json();
}

async function gradeAnswer(question, userAnswer) {
  const res = await fetch(`${BASE_URL}/answer`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      question: question,
      answer: userAnswer,
    }),
  });

  return res.json();
}

async function fetchFreeTalk(latestUserMessage) {
  // Build the full conversation for GPT:
  //   history so far + the user's latest message
  const conversationToSend = [
    ...state.freeTalkHistory,
    { role: "user", content: latestUserMessage },
  ];

  const res = await fetch(`${BASE_URL}/freetalk`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      conversation: conversationToSend,
    }),
  });

  return res.json();
}

/******************************************
 * MAIN FLOW FUNCTIONS
 ******************************************/
async function loadNextSummary() {
  // Reset Bloom level for new slide
  state.bloomIndex = 0;

  updateProgressBar();
  updateSlideCounter();

  const result = await fetchSummary(state.currentSlide);

  addMessage(
    `Slide ${state.currentSlide} Summary:\n${result.summary}`,
    "incoming"
  );

  state.freetalk = true;
  state.freeTalkHistory = []; // fresh history

  // Seed history with summary for GPT context
  state.freeTalkHistory.push({
    role: "assistant",
    content: `Here is the summary of slide ${state.currentSlide}: ${result.summary}`,
  });

  // Ask student if they want to discuss or move on
  addMessage(
    "Let me know if you'd like to discuss this slide, or say 'continue' when you're ready for questions.",
    "incoming"
  );

  isResponseGenerating = false;
}

async function loadNextQuestion() {
  updateProgressBar();
  const level = state.bloomOrder[state.bloomIndex];
  const result = await fetchQuestion(state.currentSlide, level);

  state.currentQuestion = result.question; //store the current question in state object
  addMessage(`(${level.toUpperCase()}) ${result.question}`, "incoming");

  isResponseGenerating = false;
}

async function processUserAnswer(userText) {
  /******************************************
   * 0. If already in free-talk mode, handle that
   ******************************************/
  if (state.freetalk) {
    const reply = await fetchFreeTalk(userText);

    if (reply.continue_free_talk === false) {
      // END FREE TALK — do NOT print the free-talk message
      state.freetalk = false;

      if (state.bloomIndex === 0) {
        // Free talk came after summary → move to Remember
        state.bloomIndex = 1;
      }

      addMessage("Okay, let's continue.", "incoming");
      loadNextQuestion();
    } else {
      // STILL in free talk → print reply
      addMessage(reply.reply, "incoming");
      isResponseGenerating = false;
    }

    return; // always stop normal grading flow
  }

  /******************************************
   * 1. NORMAL MODE — grade the answer
   ******************************************/
  const grading = await gradeAnswer(state.currentQuestion, userText);

  // Show explanation
  addMessage(grading.explanation, "incoming");

  /******************************************
   * 2. Decide next action
   ******************************************/
  console.log(grading.correct);
  console.log(grading);
  if (grading.grade === "correct") {
    console.log("correct answer");

    // Move to next Bloom level
    state.bloomIndex++;

    if (state.bloomIndex < state.bloomOrder.length) {
      // Ask next question on same slide
      loadNextQuestion();
    } else {
      // Finished all Bloom levels → next slide
      state.currentSlide++;
      loadNextSummary();
    }
  } else {
    /******************************************
     * INCORRECT → ENTER FREE-TALK MODE
     ******************************************/
    state.freetalk = true;
    state.freeTalkHistory = []; // reset free talk history

    // Seed history with the question + user's incorrect answer
    state.freeTalkHistory.push({
      role: "assistant",
      content: "The question was: " + state.currentQuestion,
    });

    state.freeTalkHistory.push({
      role: "user",
      content: "My answer was: " + userText,
    });

    addMessage(
      "Let's go over this together. What are you unsure about?",
      "incoming"
    );

    isResponseGenerating = false;
  }
}

/******************************************
 * FORM SUBMISSION HANDLER
 ******************************************/
typingForm.addEventListener("submit", async (e) => {
  e.preventDefault();
  if (isResponseGenerating) return;

  const userMessage = typingForm.querySelector(".typing-input").value.trim();
  if (!userMessage) return;

  typingForm.reset();
  addMessage(userMessage, "outgoing");

  isResponseGenerating = true;
  await processUserAnswer(userMessage);
});

/******************************************
 * CLEAR CHAT
 ******************************************/
deleteChatButton.addEventListener("click", () => {
  chatList.innerHTML = "";
});

/******************************************
 * INITIAL LOAD — START STUDY SESSION
 ******************************************/
// async function init() {
//   await loadLocalSlides(); // MUST wait
//   loadNextSummary();
// }
// init();
