"""
Flask backend for the Slide2Study system.
This server has four endpoints.

1. /summary
   Summary Agent
   - Takes slide text extracted on the frontend (via pdf.js).
   - Returns a concise, accurate summary of the slide.

2. /question
   Question Agent
   - Generates Bloom-level questions ("remember", "understand", "apply") based on the given slide text.
   - Uses a unified three-level prompt to ensure consistent question quality.

3. /answer
   Grader Agent
   - Evaluates the student's answer to a generated question.
   - Returns a grade ("correct" or "incorrect") along with a brief explanation.

4. /freetalk
   - Activated when the student answers incorrectly.
   - Enables open-ended clarification and guidance.
   - Returns `continue_free_talk = false` when the student indicates readiness to resume structured questioning.


Note that some of this code was generated by GPT-5.0. 
"""



from flask import Flask, request, jsonify  # Flask web framework
from dotenv import load_dotenv   # Loads environment variables from a .env fil
import os   # for accessing environment variables
import json  # for parsing JSON responses
from openai import OpenAI  # OpenAI client library
from flask_cors import CORS   # for handling Cross-Origin Resource Sharing 
from questionGenerator import question_generator_prompt   # question generation prompt
from gradeGenerator import grade_generator_prompt            # grade generation prompt
#from noteGenerator import prompt_summary_generator_generate_single_note_using_parsed_slide_text        # instead we use hardcoded prompt for generating notes


# load environment variable from .env file
# get OPENAI_API_KEY from environment variables
load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


# Initialize Flask app
app = Flask(__name__)
CORS(app)

# Check endpoint
@app.route("/")
def home():
    return {"status": "backend running"}


# summary agent ednpoint
# input slide text 
# output summary
# the correct way to do this would be to import the prompt from noteGenerator.py, but it causes issues that we dont have time to deal with
prompt_summary_generator_generate_single_note_using_parsed_slide_text = """
Task:
You will be given parsed text from one lecture slide. Your job is to produce a concise, faithful summary of the slide’s content.


Input:
- A block of text extracted directly from a single lecture slide.
- This text may contain headers, footers, slide numbers, or instructor/course labels.


Output:
- A single plain-text summary that captures all essential concepts from the slide.
- The summary must be written in clear, student-friendly language.
- Output ONLY the summary text with no headings, labels, explanations, or extra commentary.


Requirements:
1. Remove irrelevant elements such as headers, footers, slide numbers, and instructor or course information.
2. Do NOT invent new facts, examples, or interpretations not present in the slide.
3. You may rephrase, condense, and reorganize, but all important information from the slide must be preserved.
4. The summary should be short, coherent, and directly helpful for a student trying to understand the slide.


Always output only the summary.
"""
@app.route("/summary", methods=["POST"])
def summary():
    data = request.get_json()

    if not data or "slide_text" not in data:
        return {"error": "Missing slide_text in request"}, 400

    slide_text = data["slide_text"]

    try:
        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {
                    "role": "system",
                    "content": prompt_summary_generator_generate_single_note_using_parsed_slide_text
                },
                {
                    "role": "user",
                    "content": f"Summarize this slide:\n\n{slide_text}"
                }
            ]
        )
        summary_text = response.choices[0].message.content

    except Exception as e:
        return {"error": str(e)}, 500

    return {"summary": summary_text}


# question agent endpoint
# input slide text and bloom level
# output generated question
@app.route("/question", methods=["POST"])
def question():
    data = request.get_json()

    # Validate request format
    if not data or "slide_text" not in data or "level" not in data:
        return {"error": "Missing slide_text or level"}, 400

    slide_text = data["slide_text"]
    level = data["level"].lower()

    valid_levels = ["remember", "understand", "apply"]
    if level not in valid_levels:
        return {"error": "Invalid level"}, 400

    # ---- GPT Question Generation ----
    try:
        response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[
            {
                "role": "system",
                "content": question_generator_prompt
            },
            {
                "role": "user",
                "content": (
                    f"Slide text:\n{slide_text}\n\n"
                    f"Level: {level}"
                )
            }
        ]
    )

        generated_question = response.choices[0].message.content

    except Exception as e:
        return {"error": str(e)}, 500

    return {
        "level": level,
        "question": generated_question
    }


# Grader agent endpoint
# input question and student answer
# output grade and explanation
@app.route("/answer", methods=["POST"])
def answer():
    data = request.get_json()

    if not data or "question" not in data or "answer" not in data:
        return {"error": "Fields 'question' and 'answer' are required"}, 400

    question = data["question"]
    user_answer = data["answer"]

    # Call GPT evaluator
    try:
        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {
                    "role": "system",
                    "content": grade_generator_prompt
                },
                {
                    "role": "user",
                    "content": (
                        f"Question: {question}\n"
                        f"Student Answer: {user_answer}\n\n"
                        "Evaluate correctness and explain why."
                    )
                }
            ]
        )

        eval_text = response.choices[0].message.content

    except Exception as e:
        return {"error": str(e)}, 500

    # Parse grading result from GPT text
    grade = "incorrect"
    if "correct" in eval_text.lower() and "incorrect" not in eval_text.lower():
        grade = "correct"

    return {
        "grade": grade,
        "explanation": eval_text
    }

# Free-talk endpoint
# input conversation history
# output tutor response and whether to continue free talk
@app.route("/freetalk", methods=["POST"])
def freetalk():
    data = request.get_json()
    conversation = data.get("conversation", "")

    try:
        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an anatomy tutor helping a student. "
                        "You may answer questions, clarify misunderstandings, or provide explanations. "
                        "After responding, decide whether the student should remain in free-talking mode.\n\n"
                        "Respond in JSON ONLY with the following fields:\n"
                        "1. reply: your natural-language response to the student's message.\n"
                        "2. continue_free_talk: true if the student is still asking general questions, "
                        "false if they appear ready to return to structured study.\n\n"
                        "Guidelines:\n"
                        "- If the student asks a question, expresses confusion, or wants more explanation → continue_free_talk = true.\n"
                        "- If the student says things like 'okay let's continue', 'I'm ready', 'next', "
                        "'move on', 'continue studying', → continue_free_talk = false."
                    )
                },
                {
                    "role": "user",
                    "content": f"The student said: {conversation}\n\n"
                               "Return only valid JSON."
                }
            ]
        )

        # Parse JSON returned by the model
        raw_reply = response.choices[0].message.content.strip()

        # The model returns JSON as text → convert to Python dict
        result = json.loads(raw_reply)

        return jsonify(result)

    except Exception as e:
        return {"error": str(e)}, 500


# Run the Flask app
if __name__ == "__main__":
    app.run(debug=True)